// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvMLR_9iKmlGEE4ew5opXP2zOErNJsJjQ',
    appId: '1:619734707649:web:b28f98c7c464e6e5a81340',
    messagingSenderId: '619734707649',
    projectId: 'bella-store-ece11',
    authDomain: 'bella-store-ece11.firebaseapp.com',
    storageBucket: 'bella-store-ece11.appspot.com',
    measurementId: 'G-CXP0W87RW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8_h9STrD7IdufsVbWHCAH2So9SjaX07c',
    appId: '1:619734707649:android:ad12118c1b6e3823a81340',
    messagingSenderId: '619734707649',
    projectId: 'bella-store-ece11',
    storageBucket: 'bella-store-ece11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUdjKTRcbeVal_Kpj4bylUBxr4Ok2rhCA',
    appId: '1:619734707649:ios:2e1e1f4a1f7ae0eba81340',
    messagingSenderId: '619734707649',
    projectId: 'bella-store-ece11',
    storageBucket: 'bella-store-ece11.appspot.com',
    iosClientId: '619734707649-q4a41sao9f6g18pi9e5npnd0o63adids.apps.googleusercontent.com',
    iosBundleId: 'com.example.bellaApp',
  );
}
